#!/bin/bash -v
# Bootstrap all stuff needed for a Debian Wheezy base Jenkins-CI setup
# Must be run as user root
aptitude install git etckeeper
echo puppet | tee --append /etc/.gitignore
cd /etc && git commit -a
git clone https://github.com/ngiger/srv_elexis.git /etc/puppet
aptitude update
aptitude remove puppet facter
apt-get  build-dep puppet augeas-tools
aptitude install libaugeas-ruby augeas-tools gcc build-essential zlib1g zlib1g-dev
gem install puppet facter librarian-puppet  --no-ri --no-rdoc
cd /etc/puppet
puppet /etc/puppet/manifest/site.pp

