#!/bin/bash -v
export params=$*
export abs_file=`readlink -f $0`
export abs_dir=`dirname  $abs_file`
if [ -z "$*" ]
then
  export params=${abs_dir}/manifests/site.pp
fi
echo params are $* as var are $params
if [ `which librarian-puppet` ]
then
  librarian-puppet install --verbose
else
  echo librarian-puppet not found
fi
sudo /opt/puppetlabs/bin/puppet apply --modulepath=${abs_dir}/modules ${params}