#!/bin/bash -v
export params=$*
if [ -z "$*" ]
then
  export params=/vagrant/manifests/site.pp
fi
echo params are $* as var are $params
if [ `which librarian-puppet` ]
then
  librarian-puppet install --verbose
else
  echo librarian-puppet not found
fi
sudo /opt/puppetlabs/bin/puppet apply --modulepath=/vagrant/modules ${params}