name    'ngiger/elexis-jenkins'
version '0.0.1'
source 'http://github.com/ngiger/elexis-jenkins'
author 'ngiger'
license 'Apache License, Version 2.0'
summary 'Puppet module for running the Jenkins-CI for Elexis'
description 'UNKNOWN'
project_page 'http://elexis.info'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
