source "https://rubygems.org"
gem 'puppetlabs_spec_helper'
gem 'puppet-syntax'
gem 'puppet-lint'
gem 'rspec'
gem 'puppet', '~>4.3.0'
gem 'hiera-puppet-helper'
#gem 'syck'
gem 'rspec-puppet'
gem 'rake'
# use rodjek to get coverage on rspec
#gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'