<?php
# This file was automatically generated by the MediaWiki 1.19.5-1+deb7u1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "Elexis-Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://wiki.elexis.info";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "/elexis_135.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "apache@srv.elexis.info";
$wgPasswordSender   = "apache@srv.elexis.info";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "elexis_wiki";
$wgDBuser           = "elexis";
$wgDBpassword       = "elexisTest";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgAllowCopyUploads = true;

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "de-ch";

$wgSecretKey = "cddbd0548a21f0fbf73b469317853c5b27c4bb67fb0c01e4bb21e49a52ef6c7a";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a13ffd507ff9cb23";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# debian-specific include:
if (is_file("/etc/mediawiki-extensions/extensions.php")) {
	include("/etc/mediawiki-extensions/extensions.php");
}

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['delete'] = true;
$wgGroupPermissions['Trusted']['delete'] = true;
$wgGroupPermissions['Trusted'] = $wgGroupPermissions['user'];
$wgGroupPermissions['user'   ]['edit']          = false;
$wgGroupPermissions['Trusted']['edit']          = true;

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
if (file_exists( "$IP/extensions/Collection/Collection.php" )) {
  require_once( "$IP/extensions/Collection/Collection.php" );
}

if (file_exists( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" )) {
  require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
}

if (file_exists( "$IP/extensions/LanguageSelector/LanguageSelector.php" )) {
  require_once( "$IP/extensions/LanguageSelector/LanguageSelector.php" );
  # $wgLanguageSelectorLanguages=array("en", "de-ch");
  # $wgLanguageSelectorLocation = LANGUAGE_SELECTOR_NONE;
  $wgLanguageSelectorLocation = LANGUAGE_SELECTOR_USE_CONTENT_LANG;

}

if (file_exists( "$IP/extensions/Vector/Vector.php" )) {
  require_once( "$IP/extensions/Vector/Vector.php" );
}

if (file_exists("$IP/extensions/WikiEditor/WikiEditor.php" )) {
  require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );
}

if (file_exists("$IP/extensions/BlockAndNuke/BlockAndNuke.php" )) {
  require_once("$IP/extensions/BlockAndNuke/BlockandNuke.php");
  # See http://www.mediawiki.org/wiki/Extension:BlockAndNuke
  $wgWhitelist = ("$IP/extensions/BlockAndNuke/whitelist.txt");
}

if (file_exists("$IP/extensions/Nuke/Nuke.php" )) {
  require_once "$IP/extensions/Nuke/Nuke.php";
}

# End of automatically generated settings.
# Add more configuration options below.

$wgScriptPath       = "";
$wgArticlePath      = "/$1";
$wgUsePathInfo      = true;
$wgAllowImageMoving = true;
$wgGroupPermissions['Trusted']['move']          = true;
$wgGroupPermissions['Trusted']['movefile']      = true;


$wgCollectionPODPartners = false;
# $wgCollectionMWServeURL = 'http://wiki.elexis.info/cache';
# $wgCollectionMWServeURL = 'http://144.76.170.222:8898/cache';
# $wgCollectionMWServeURL = 'http://localhost:8898/cache';
$wgCollectionMWServeURL = 'http://wiki.elexis.info:8898/cache';

$wgCollectionMWServeCredentials = "elexis:F@d9J52azXn6";

$wgCollectionMWServeCredentials = "elexis:F@d9J52azXn6";

# $wgFileExtensions[] = 'pdf';
# $wgFileExtensions[] = 'odt';
# $wgFileExtensions[] = 'ods';
# $wgFileExtensions[] = 'png';
# $wgFileExtensions[] = 'PNG';

#$wgFileExtensions = array('png','gif','jpg','jpeg','doc','xls','mpp','pdf','ppt','tiff','bmp','docx', 'xlsx', 'pptx','ps','odt','ods','odp','odg');
$wgFileExtensions = array('png','gif','jpg','jpeg', 'pdf', 'tiff','bmp', 'odt','ods','odp','odg');
# $wgFileExtensions = array('png','gif','jpg','jpeg', 'pdf', 'ods, 'odt', 'PNG', 'JPG');
$wgFileBlacklist = array_diff( $wgFileBlacklist, array ('png') );

#// By default nobody can use this function, enable for bureaucrat?
#$wgGroupPermissions['bureaucrat']['usermerge'] = true;
#$wgUserMergeProtectedGroups = array( 'trusted' );
#$wgUserMergeUnmergeable = array( 'sysop', 'trusted' );


$wgEnableAPI = true;

